# ## Base Info
# name: gpio_util
# version: v1.0.0
# description: common util
# type: common
# tag: application
# keywords:
#   - base
# license: Apache license v2.0

# ## Compile & Link Info
# build_config:
#   include:
#     - include
#   internal_include:
#   libs:
#   libpath:

# source_file:
#   - src/*.c

# ## Install Info
# install:
#   - dest: "include/"
#     source:
