#ifndef WIFI_DEF_H
#define WIFI_DEF_H

#pragma pack(push, 1)


///////////////////////YINGHUA_JIWEI_WIFI//////////////////////////
#define YINGHUA_JIWEI_WIFI_HEADER1  0xAA
#define YINGHUA_JIWEI_WIFI_HEADER2  0x55

enum E_YINGHUA_JIWEI_WIFI_CMD
{
    E_YINGHUA_JIWEI_WIFI_NONE = 0,
    E_YINGHUA_JIWEI_WIFI_CONFIG = 0x01,
    E_YINGHUA_JIWEI_WIFI_ACK = 0x02,
    E_YINGHUA_JIWEI_WIFI_DOOR_STATE = 0x03,
    E_YINGHUA_JIWEI_WIFI_POWER_DOWN = 0x04,
    E_YINGHUA_JIWEI_WIFI_RESET_NETWORK = 0x05,
    E_YINGHUA_JIWEI_WIFI_GET_ID = 0x06,
    E_YINGHUA_JIWEI_WIFI_SET_ID = 0x07,
    E_YINGHUA_JIWEI_WIFI_STATE = 0x08,
    E_YINGHUA_JIWEI_WIFI_STATE_ACK = 0x09,
    E_YINGHUA_JIWEI_WIFI_UPGRADE = 0x0A,
    E_YINGHUA_JIWEI_WIFI_UPGRADE_ACK = 0x0B,
    E_YINGHUA_JIWEI_WIFI_CHECK_WIFI = 0x0C,
    E_YINGHUA_JIWEI_WIFI_CHECK_WIFI_ACK = 0x0D,
    E_YINGHUA_JIWEI_WIFI_SET_HOTSPOT = 0x0E,
    E_YINGHUA_JIWEI_WIFI_SET_HOTSPOT_ACK = 0x0F,
    E_YINGHUA_JIWEI_WIFI_GET_TIME = 0x10,
    E_YINGHUA_JIWEI_WIFI_GET_TIME_ACK = 0x11,
    E_YINGHUA_JIWEI_WIFI_REMOTE_UNLOCK = 0x13,
    E_YINGHUA_JIWEI_WIFI_SEND_PHOTO = 0x1C,
    E_YINGHUA_JIWEI_WIFI_NET_STATUS = 0x23,
    E_YINGHUA_JIWEI_WIFI_CE_STATUS = 0x28,
    E_YINGHUA_JIWEI_WIFI_CE_STATUS_ACK = 0x29,
    E_YINGHUA_JIWEI_WIFI_GET_CATEYE_STATUS = 0x2D,
    E_YINGHUA_JIWEI_WIFI_GET_CATEYE_STATUS_ACK = 0x2C,
    E_YINGHUA_JIWEI_WIFI_MEDIA_REQ = 0x2F,
    E_YINGHUA_JIWEI_WIFI_MEDIA_REQ_ACK = 0x2E,
    E_YINGHUA_JIWEI_WIFI_WIFI_MODULE_STATUS = 0x2B,
    E_YINGHUA_JIWEI_WIFI_WIFI_MODULE_STATUS_ACK = 0x2A,
    E_YINGHUA_JIWEI_WIFI_AUDIO_PUSH = 0x31,
    E_YINGHUA_JIWEI_WIFI_AUDIO_PULL = 0x33,
    E_YINGHUA_JIWEI_WIFI_SCAN_QR_ACK = 0x34,
    E_YINGHUA_JIWEI_WIFI_SCAN_QR = 0x35,
    E_YINGHUA_JIWEI_WIFI_REPORT_QR_RES = 0x36,
    E_YINGHUA_JIWEI_WIFI_REPORT_QR_RES_ACK = 0x37,
    E_YINGHUA_JIWEI_WIFI_PLAY_AUDIO = 0x39,
    E_YINGHUA_JIWEI_WIFI_PLAY_AUDIO_ACK = 0x38,
};

enum E_YINGHUA_JIWEI_WIFI_STATE
{
    E_YINGHUA_JIWEI_WIFI_STATE_LOCKED = 0x00,
    E_YINGHUA_JIWEI_WIFI_STATE_UNLOCKED = 0x01,
    E_YINGHUA_JIWEI_WIFI_STATE_ALARM = 0x02,
    E_YINGHUA_JIWEI_WIFI_STATE_REQUEST = 0x03,
    E_YINGHUA_JIWEI_WIFI_STATE_ALERT = 0x04,
};

enum E_YINGHUA_JIWEI_WIFI_ALERT_TYPE
{
    E_YINGHUA_JIWEI_WIFI_ALERT_TYPE_MISS_KEY = 0x01,
    E_YINGHUA_JIWEI_WIFI_ALERT_TYPE_LOCKED = 0x02,
    E_YINGHUA_JIWEI_WIFI_ALERT_TYPE_LOW_BATT = 0x08,
    E_YINGHUA_JIWEI_WIFI_ALERT_TYPE_BELL = 0x0C
};

enum E_YINGHUA_JIWEI_WIFI_LOG_TYPE
{
    E_YINGHUA_JIWEI_WIFI_LOG_TYPE_MAIN = 0,
    E_YINGHUA_JIWEI_WIFI_LOG_FINGERPRINT = 1,
    E_YINGHUA_JIWEI_WIFI_LOG_PASSWORD = 2,
    E_YINGHUA_JIWEI_WIFI_LOG_CARD = 3,
    E_YINGHUA_JIWEI_WIFI_LOG_KEY = 4,
    E_YINGHUA_JIWEI_WIFI_LOG_PHONE = 5,
    E_YINGHUA_JIWEI_WIFI_LOG_FACE = 6,
    E_YINGHUA_JIWEI_WIFI_LOG_HAND = 7
};

enum E_YINGHUA_JIWEI_WIFI_ALARM_TYPE
{
    E_YINGHUA_JIWEI_WIFI_ALARM_TYPE_XX      = 0x00,
    E_YINGHUA_JIWEI_WIFI_ALARM_TYPE_FORCE   = 0x01,
    E_YINGHUA_JIWEI_WIFI_ALARM_TYPE_FP      = 0x02,
    E_YINGHUA_JIWEI_WIFI_ALARM_TYPE_PASS    = 0x03,
    E_YINGHUA_JIWEI_WIFI_ALARM_TYPE_CARD    = 0x04,
    E_YINGHUA_JIWEI_WIFI_ALARM_TYPE_KEY     = 0x05,
    E_YINGHUA_JIWEI_WIFI_ALARM_TYPE_REMOTE  = 0x06,
    E_YINGHUA_JIWEI_WIFI_ALARM_TYPE_UNLOCK_TWICE = 0x08,
    E_YINGHUA_JIWEI_WIFI_ALARM_TYPE_TESLA   = 0x09,
    E_YINGHUA_JIWEI_WIFI_ALARM_TYPE_RESERVED = 0x0A,
};

enum WifiRet
{
    WIFI_OK = 0,
    WIFI_DATA_ERROR = 1,
    WIFI_FAILED = 2
};

typedef struct _tagYINGHUA_JIWEI_WIFI_CMD
{
    unsigned char bHeader1;    //0x55AA
    unsigned char bHeader2;    //0x55AA
    unsigned char bCmd;
    unsigned char bData[6];
    unsigned char bCheckSum;
} YINGHUA_JIWEI_WIFI_CMD;

///////////////////////GESANG_SIGE_WIFI//////////////////////////

#define GESANG_SIGE_WIFI_HEADER     0xAA

enum E_GESANG_SIGE_CMD
{
    E_GESANG_SIGE_CONFIG = 0x01,
    E_GESANG_SIGE_RESET_NETWORK = 0x02,
    E_GESANG_SIGE_REMOTE_UNLOCK = 0x03,
    E_GESANG_SIGE_SEND_STATE = 0x04,
    E_GESANG_SIGE_SEND_ALERT = 0x05,
    E_GESANG_SIGE_SEND_POWER_DOWN = 0x06,
};

enum E_GESANG_SIGE_ACK
{
    E_GESANG_SIGE_OK = 0,
    E_GESANG_SIGE_DATA_ERROR = 1,
    E_GESANG_SIGE_FAILED = 2,
};

enum E_GESANG_SIGE_STATE
{
    E_GESANG_SIGE_STATE_OPEN = 0x1,
    E_GESANG_SIGE_STATE_CLOSE = 0x2,
};

enum E_GESANG_SIGE_STATE_MODE
{
    E_GESANG_SIGE_STATE_MODE_PASS = 0x00,
    E_GESANG_SIGE_STATE_MODE_KEY = 0x01,
    E_GESANG_SIGE_STATE_MODE_FP = 0x02,
    E_GESANG_SIGE_STATE_MODE_CARD = 0x03,
    E_GESANG_SIGE_STATE_MODE_REMOTE = 0x04,
    E_GESANG_SIGE_STATE_MODE_FACE = 0x05,
    E_GESANG_SIGE_STATE_MODE_HAND = 0x06,
};

enum E_GESANG_SIGE_ALERT
{
    E_GESANG_SIGE_ALERT_LOW_BATT = 0x01,
    E_GESANG_SIGE_ALERT_SIREN = 0x2,
    E_GESANG_SIGE_ALERT_THREAT = 0x3
};

typedef struct _tagGESANG_SIGE_WIFI_CMD
{
    unsigned char bHeader;    //0xAA
    unsigned char bCmd;
    unsigned char bData[4];
    unsigned char bCheckSum;
} GESANG_SIGE_WIFI_CMD;



union WIFI_CMD
{
    YINGHUA_JIWEI_WIFI_CMD  xYongHua_JiWei;
    GESANG_SIGE_WIFI_CMD    xGesang_Sige;
    unsigned char           abData[16];
};

enum
{
    E_WIFI_STATE_NONE = 0,
    E_WIFI_STATE_MOTOR = 1,
    E_WIFI_STATE_ALARM = 2,
    E_WIFI_STATE_REQUEST = 3,
    E_WIFI_STATE_ALERT = 4
};

enum
{
    E_W_MOTOR_CONTROL_FP = 0x01,
    E_W_MOTOR_CONTROL_PASS = 0x02,
    E_W_MOTOR_CONTROL_CARD = 0x03,
    E_W_MOTOR_CONTROL_KEY = 0x04,
    E_W_MOTOR_CONTROL_PHONE = 0x05,
    E_W_MOTOR_CONTROL_FACE = 0x06,
    E_W_MOTOR_CONTROL_HAND = 0x07,
    E_W_MOTOR_CONTROL_BTN_OPEN = 0x10,
    E_W_MOTOR_CONTROL_BTN_CLOSE = 0x11,
    E_W_MOTOR_CONTROL_AUTO_CLOSE = 0x12,
    E_W_MOTOR_CONTROL_FRONT_CLOSE = 0x13,
    E_W_MOTOR_CONTROL_KEEP_OPEN_OPEN = 0x14,
    E_W_MOTOR_CONTROL_KEEP_OPEN_CLOSE = 0x15,
};

enum
{
    E_W_ALARM_FACE = 0x00,
    E_W_ALARM_FP = 0x01,
    E_W_ALARM_PASS = 0x02,
    E_W_ALARM_CARD = 0x03,
    E_W_ALARM_KEY = 0x04,
    E_W_ALARM_PHONE = 0x05,
    E_W_ALARM_HAND = 0x06,
};

enum
{
    E_W_ALERT_LOW_BATT = 0x00,
    E_W_ALERT_DOOR_BELL = 0x01,
};

typedef struct _tagWIFI_CONTROL
{
    int         iValid;
    int         iID;
    int         iState;
    int         iData;
} WIFI_CONTROL;

#pragma pack(pop)


#endif // ZIGBEE_DEF_H
