
## 第一部分： 基础信息
name: zbar                                          # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: develop                                    # <必选项> 组件版本号
description: zbar test                              # <必选项> 建议至少20字以上
type: common                                        # <必选项> 组件类型，为：solution, chip, board, common, sdk
tag:                                                # <可选项> 组件分类，缺省值： ''
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本
# sdk_chip:                                # <可选项> 该组件依赖sdk组件，合理的依赖才能保证组件能编译、使用
#   - sdk_chip_csky_dummy: v7.4.0
#   - sdk_chip_riscv_dummy: v7.4.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.4.0
#   - aos: v7.4.0

#depends:
#  - lwip: v7.4.7


## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  cflag:
    -Wno-unused-variable -Wno-error=parentheses
  cxxflag:
    -enable-threads=posix
  include:
    - include
  internal_include:
    - include
  define:
    ENABLE_CODE128: 1
    ENABLE_CODE39: 1
    ENABLE_EAN: 1
    ENABLE_I25: 1
    ENABLE_QRCODE: 64
    HAVE_ATEXIT: 1
    HAVE_FCNTL_H: 1
    HAVE_DLFCN_H: 1
    HAVE_FEATURES_H: 1
    HAVE_GETPAGESIZE: 1
    HAVE_ICONV: 1
    HAVE_INTTYPES_H: 1
    HAVE_LIBPTHREAD: 1
    HAVE_MEMORY_H: 1
    HAVE_MEMSET: 1
    HAVE_POLL_H: 1
    HAVE_PTHREAD_H: 1
    HAVE_SETENV: 1
    HAVE_STDINT_H: 1
    HAVE_STDLIB_H: 1
    HAVE_STRINGS_H: 1
    HAVE_STRING_H: 1
    HAVE_SYS_IOCTL_H: 1
    HAVE_SYS_IPC_H: 1
    HAVE_SYS_MMAN_H: 1
    HAVE_SYS_PARAM_H: 1
    HAVE_SYS_SHM_H: 1
    HAVE_SYS_STAT_H: 1
    HAVE_SYS_TIMES_H: 1
    HAVE_SYS_TIME_H: 1
    HAVE_SYS_TYPES_H: 1
    HAVE_UINTPTR_T: 1
    HAVE_UNISTD_H: 1
    ICONV_CONST: 1
    LIB_VERSION_MAJOR: 0
    LIB_VERSION_MINOR: 2
    LIB_VERSION_REVISION: 0
    SOCKLEN_T: ".libs/"
    PACKAGE: "zbar"
    PACKAGE_BUGREPORT: "spadix@users.sourceforge.net"
    PACKAGE_NAME: "zbar"
    PACKAGE_STRING: "zbar 0.10"
    PACKAGE_TARNAME: "zbar"
    PACKAGE_URL: ""
    PACKAGE_VERSION: "0.10"
    STDC_HEADERS: 1
    VERSION: "0.10"
    X_DISPLAY_MISSING: 1
    ZBAR_VERSION_MAJOR: 0
    ZBAR_VERSION_MINOR: 10
    __USE_UNIX98: 1





source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
  - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件


## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y
def_config:
  LOCALE_NOT_USED: y

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相对路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
install:
  - dest: "include/"
    source:
      - "include/*.h"

## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相对路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
