#include "config_vars.h"
#include "engine_inner_param.h"

st_file_offsize g_part_files[] = {
#if (N_MAX_PERSON_NUM)
    {FN_WNO_DICT_PATH, FN_WNO_DICT_SIZE_REAL, FN_WNO_DICT_SIZE, DNN_FEAT_CHECKSUM, FN_CRYPTO_AES | FN_CRYPTO_AES_DYN_ID2 | FN_CRYPTO_ZSTD, MY_32ALIGNED(0x100), "FN_WNO_DICT"},
    {FN_DETECT_DICT_PATH, FN_DETECT_DICT_SIZE_REAL, FN_DETECT_DICT_SIZE, DNN_DETECT_CHECKSUM, FN_CRYPTO_AES | FN_CRYPTO_ZSTD, MY_32ALIGNED(0x100), "FN_DETECT_DICT"},
    {FN_DLAMK_DICT_PATH, FN_DLAMK_DICT_SIZE_REAL, FN_DLAMK_DICT_SIZE, DNN_MODELING_CHECKSUM, FN_CRYPTO_AES | FN_CRYPTO_ZSTD, MY_32ALIGNED(0x100), "FN_DLAMK_DICT"},
#if (DESMAN_ENC_MODE == 0)
    {FN_OCC_DICT_PATH, FN_OCC_DICT_SIZE_REAL, FN_OCC_DICT_SIZE, DNN_OCC_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0x100), "FN_OCC_DICT"},
    {FN_ESN_DICT_PATH, FN_ESN_DICT_SIZE_REAL, FN_ESN_DICT_SIZE, DNN_ESN_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0x100), "FN_ESN_DICT"},
#endif // DESMAN_ENC_MODE
    {FN_A1_DICT_PATH, FN_A1_DICT_SIZE_REAL, FN_A1_DICT_SIZE, DNN_2D_LIVE_A1_CHECKSUM, FN_CRYPTO_AES | FN_CRYPTO_ZSTD, MY_32ALIGNED(0x100), "FN_A1_DICT"},
#if (ENGINE_USE_TWO_CAM)
    {FN_B_DICT_PATH, FN_B_DICT_SIZE_REAL, FN_B_DICT_SIZE, DNN_2D_LIVE_B_CHECKSUM, FN_CRYPTO_AES | FN_CRYPTO_ZSTD, MY_32ALIGNED(0x100), "FN_B_DICT"},
    {FN_B2_DICT_PATH, FN_B2_DICT_SIZE_REAL, FN_B2_DICT_SIZE, DNN_2D_LIVE_B2_CHECKSUM, FN_CRYPTO_AES | FN_CRYPTO_ZSTD, MY_32ALIGNED(0x100), "FN_B2_DICT"},
#endif // ENGINE_USE_TWO_CAM
    {FN_C_DICT_PATH, FN_C_DICT_SIZE_REAL, FN_C_DICT_SIZE, DNN_3D_LIVE_CHECKSUM, FN_CRYPTO_AES | FN_CRYPTO_ZSTD, MY_32ALIGNED(0x100), "FN_C_DICT"},
#endif // N_MAX_PERSON_NUM
#if (N_MAX_HAND_NUM)
#if (!N_MAX_PERSON_NUM)
    {FN_WNOH_DICT_PATH, FN_WNOH_DICT_SIZE_REAL, FN_WNOH_DICT_SIZE, DNN_FEAT_HAND_CHECKSUM, FN_CRYPTO_AES | FN_CRYPTO_AES_DYN_ID2 | FN_CRYPTO_ZSTD, MY_32ALIGNED(0x100), "FN_WNOH_DICT"},
#endif
    {FN_DETECT_H_DICT_PATH, FN_DETECT_H_DICT_SIZE_REAL, FN_DETECT_H_DICT_SIZE, DNN_DETECT_HAND_CHECKSUM, FN_CRYPTO_AES | FN_CRYPTO_ZSTD, MY_32ALIGNED(0x100), "FN_DETECT_H_DICT"},
    {FN_DLAMK_H_DICT_PATH, FN_DLAMK_H_DICT_SIZE_REAL, FN_DLAMK_H_DICT_SIZE, DNN_MODELING_HAND_CHECKSUM, FN_CRYPTO_AES | FN_CRYPTO_ZSTD, MY_32ALIGNED(0x100), "FN_DLAMK_H_DICT"},
#if (N_MAX_PERSON_NUM)
    {FN_WNOH_DICT_PATH, FN_WNOH_DICT_SIZE_REAL, FN_WNOH_DICT_SIZE, DNN_FEAT_HAND_CHECKSUM, FN_CRYPTO_AES | FN_CRYPTO_AES_DYN_ID2 | FN_CRYPTO_ZSTD, MY_32ALIGNED(0x100), "FN_WNOH_DICT"},
#endif
    {FN_H_LIVE_DICT_PATH, FN_H_LIVE_DICT_SIZE_REAL, FN_H_LIVE_DICT_SIZE, DNN_LIVE_HAND_CHECKSUM, FN_CRYPTO_AES | FN_CRYPTO_ZSTD, MY_32ALIGNED(0x100), "FN_H_LIVE_DICT"},
#endif // N_MAX_HAND_NUM
#if (USE_TWIN_ENGINE)
    {FN_H1_DICT_PATH, FN_H1_DICT_SIZE_REAL, FN_H1_DICT_SIZE, DNN_H_1_CHECKSUM, FN_CRYPTO_AES | FN_CRYPTO_AES_DYN_ID2, MY_32ALIGNED(0x2000), "FN_H1_DICT"},
    {FN_H2_DICT_PATH, FN_H2_DICT_SIZE_REAL, FN_H2_DICT_SIZE, DNN_H_2_CHECKSUM, FN_CRYPTO_NONE, MY_32ALIGNED(0x2000), "FN_H2_DICT"},
#endif
    {FN_FACE_IR_BIN_PATH, FN_FACE_IR_BIN_SIZE_REAL, FN_FACE_IR_BIN_SIZE, FN_FACE_IR_BIN_CHKSUM, FN_CRYPTO_ZSTD, MY_32ALIGNED(0), "FN_FACE_IR_BIN"},
#if (USE_UAC_MODE)
    {FN_TESTAUDIO_PCM_PATH, FN_TESTAUDIO_PCM_SIZE_REAL, FN_TESTAUDIO_PCM_SIZE, 0x60196019, FN_CRYPTO_ZSTD, 0, "FN_TESTAUDIO_PCM"},
#endif
    {FN_ISP_IR_BIN_PATH, FN_ISP_IR_BIN_SIZE_REAL, FN_ISP_IR_BIN_SIZE, 0xdcf8b2df, FN_CRYPTO_ZSTD, MY_32ALIGNED(0), "FN_ISP_IR_BIN"},
    {NULL, 0, 0},
};

unsigned char g_part_crypto_aes_key[] = { 
    0x33, 0xbf, 0x55, 0xc7, 0x58, 0x3f, 0x42, 0xa5, 
    0x91, 0x87, 0x6e, 0xdc, 0x60, 0xc1, 0x56, 0xbc
};