#include "config_vars.h"
#include "engine_inner_param.h"

st_file_offsize g_part_files[] = {
    {FN_WNO_DICT_PATH, FN_WNO_DICT_SIZE, DNN_FEAT_CHECKSUM, FN_CRYPTO_AES | FN_CRYPTO_AES_DYN_ID2, MY_32ALIGNED(0x7200)},
    {FN_DETECT_DICT_PATH, FN_DETECT_DICT_SIZE, DNN_DETECT_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0x1540)},
    {FN_DLAMK_DICT_PATH, FN_DLAMK_DICT_SIZE, DNN_MODELING_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0x1540)},
#if (DESMAN_ENC_MODE == 0)
    {FN_OCC_DICT_PATH, FN_OCC_DICT_SIZE, DNN_OCC_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0)},
    {FN_ESN_DICT_PATH, FN_ESN_DICT_SIZE, DNN_ESN_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0)},
#endif // DESMAN_ENC_MODE
    {FN_A1_DICT_PATH, FN_A1_DICT_SIZE, DNN_2D_LIVE_A1_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0x1540)},
    {FN_A2_DICT_PATH, FN_A2_DICT_SIZE, DNN_2D_LIVE_A2_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0x1540)},
#if (ENGINE_USE_TWO_CAM)
    {FN_B_DICT_PATH, FN_B_DICT_SIZE, DNN_2D_LIVE_B_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0x1540)},
    {FN_B2_DICT_PATH, FN_B2_DICT_SIZE, DNN_2D_LIVE_B2_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0x1540)},
#endif // ENGINE_USE_TWO_CAM
    {FN_C_DICT_PATH, FN_C_DICT_SIZE, DNN_3D_LIVE_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0x1540)},
#if (USE_RENT_ENGINE)
    {FN_DETECT_C_DICT_PATH, FN_DETECT_C_DICT_SIZE, DNN_DETECT_C_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0x3E20)},
#endif
#if (N_MAX_HAND_NUM)
    {FN_DETECT_H_DICT_PATH, FN_DETECT_H_DICT_SIZE, DNN_DETECT_HAND_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0x1540)},
    {FN_DLAMK_H_DICT_PATH, FN_DLAMK_H_DICT_SIZE, DNN_MODELING_HAND_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0x1540)},
    {FN_CH_DICT_PATH, FN_CH_DICT_SIZE, DNN_CHECKVALID_HAND_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0x1540)},
    {FN_WNOH_DICT_PATH, FN_WNOH_DICT_SIZE, DNN_FEAT_HAND_CHECKSUM, FN_CRYPTO_AES, MY_32ALIGNED(0x5690)},
#endif // N_MAX_HAND_NUM
#if (USE_TWIN_ENGINE)
    {FN_H1_DICT_PATH, FN_H1_DICT_SIZE, DNN_H_1_CHECKSUM, FN_CRYPTO_NONE, MY_32ALIGNED(0)},
    {FN_H2_DICT_PATH, FN_H2_DICT_SIZE, DNN_H_2_CHECKSUM, FN_CRYPTO_NONE, MY_32ALIGNED(0)},
#endif
    {FN_FACE_IR_BIN_PATH, FN_FACE_IR_BIN_SIZE, 0xafb4e4d6, FN_CRYPTO_NONE, 0},
#if (USE_UAC_MODE)
    {FN_TESTAUDIO_PCM_PATH, FN_TESTAUDIO_PCM_SIZE, 0x60196019, FN_CRYPTO_NONE, 0},
#endif
    {NULL, 0, 0},
};

unsigned char g_part_crypto_aes_key[] = { 
    0x33, 0xbf, 0x55, 0xc7, 0x58, 0x3f, 0x42, 0xa5, 
    0x91, 0x87, 0x6e, 0xdc, 0x60, 0xc1, 0x56, 0xbc
};