
## 第一部分： 基础信息
name: sdk_chip_cv1810x                               # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: develop                                    # <必选项> 组件版本号
description: the sdk chip for cv1810x                # <必选项> 建议至少20字以上
type: sdk                                           # <必选项> 组件类型，为：solution, chip, board, common, sdk

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - yoc_kernel: develop
  - libc_stub: develop
  - posix: develop
  - vfs: develop
  - littlefs: develop
  - netmgr: develop
  - cjson: develop
#  - mpegts: develop
  - at: develop
  - cv1810x_evb: develop
#  - cv181xc_evb: develop
  - chip_cv181x: develop
#  - g711: develop
  - ntp: develop
#  - drv_wifi_hi3861l: develop
  - drv_snd_cv181x: develop
  - drv_wifi_rtl8723ds: deveop
  - drv_bt_rtl8723ds: deveop
  - lwip: develop
  - mbedtls: develop
  - minialsa: develop
  - drv_sdmmc: develop
  - fatfs: develop
  - cvi_mmf_sdk_cv181xx: develop
  - cherryusb: develop
  - ble_host: develop

