mtb_version: 4
chip: cv181xc_qfn

diff:
  fota_version: 0
  ram_buf: 50           #DEC     KB   ( max ram need)
  flash_buf: 16         #DEC     KB   ( buffer size)
  flash_sector: 4096    #DEC     byte ( flash sector)
  diff_mode: 010        #BIN
  double_control: 1

storages:
  - name: spinor            # eflash/spinor/spinand/emmc_boot1/emmc_boot2/emmc_user/emmc_rpmb/sd/usb
    base_address: 0         # 存储基地址，比如FLASH的基地址
    run_base_address: 0x80000000 # base address of Storage
    sector: 4096            # Bytes
    size: 16777216          # Total Bytes
  - name: usb               # eflash/spinor/spinand/emmc_boot1/emmc_boot2/emmc_user/emmc_rpmb/sd/usb
    base_address: 0         # 存储基地址，比如FLASH的基地址
    run_base_address: 0x8000C000 # base address of Storage
    block: 512              # Bytes
    size: 0                 # Total Bytes
    hot_plug: true
  - name: sd                # eflash/spinor/spinand/emmc_boot1/emmc_boot2/emmc_user/emmc_rpmb/sd/usb
    base_address: 0         # 存储基地址，比如FLASH的基地址
    run_base_address: 0x8000C000 # base address of Storage
    block: 512              # Bytes
    size: 0                 # Total Bytes
    hot_plug: true

partitions:
  - { name: boot0,  address: 0x000000, size: 0x00C000, index: 0, filename: fip_fsbl.bin}                                 # 48 KB
  - { name: boot,   address: 0x00C000, size: 0x020000, index: 0, filename: boot, load_addr: 0x8000C000 }          # 128KB
  - { name: imtb,   address: 0x02C000, size: 0x002000, index: 0, filename: imtb}                                 # 8 KB
  - { name: prim,   address: 0x02E000, size: 0x390000, index: 0, filename: prim, load_addr: 0x80040000, car: xz }          # 3 MB
  - { name: misc,   address: 0x3BE000, size: 0x12000, index: 0, filename: misc }                                 # 0.5 MB
  - { name: pwx,   address: 0x3D0000, size: 0xA80000, index: 0, filename: pwx }                                 # 4 MB
  - { name: pusr1,   address: 0xE50000, size: 0xD0000, index: 0, filename: pusr1 }                                 # 
  - { name: pusr2,   address: 0xF20000, size: 0xD0000, index: 0, filename: pusr2 }                                 # 
  - { name: pst,   address: 0xFF0000, size: 0x10000, index: 0, filename: pst }                                   # 
#  - { name: kv,     address: 0xFAE000, size: 0x010000, index: 0 }                                # 64 KB
  # - { name: spiffs, address: 0xCD0000, size: 0x100000, index: 0, filename: lfs.bin }            # 1 MB
  # - { name: cxrot,  address: 0xFBE000, size: 0x001000, index: 0  }                                # 4 KB
  # - { name: cxuser, address: 0xFBF000, size: 0x004000, index: 0  }                                # 16 KB
  # - { name: cxface, address: 0xFC3000, size: 0x03C000, index: 0  }                                # 240 KB
  - { name: fatfs,  address: 0x000000, size: 0, index: 2 }                                        # size = 0 let device decide size
